/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageUsersRouteImport } from './routes/manage.users'
import { Route as ManageSocialRouteImport } from './routes/manage.social'
import { Route as ManageResetRouteImport } from './routes/manage.reset'
import { Route as ManageRedirectRouteImport } from './routes/manage.redirect'
import { Route as ManageLoginRouteImport } from './routes/manage.login'
import { Route as ManageLocationRouteImport } from './routes/manage.location'
import { Route as ManageFormRouteImport } from './routes/manage.form'
import { Route as ManageAssetRouteImport } from './routes/manage.asset'

const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUsersRoute = ManageUsersRouteImport.update({
  id: '/manage/users',
  path: '/manage/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSocialRoute = ManageSocialRouteImport.update({
  id: '/manage/social',
  path: '/manage/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageResetRoute = ManageResetRouteImport.update({
  id: '/manage/reset',
  path: '/manage/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRedirectRoute = ManageRedirectRouteImport.update({
  id: '/manage/redirect',
  path: '/manage/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageLoginRoute = ManageLoginRouteImport.update({
  id: '/manage/login',
  path: '/manage/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageLocationRoute = ManageLocationRouteImport.update({
  id: '/manage/location',
  path: '/manage/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageFormRoute = ManageFormRouteImport.update({
  id: '/manage/form',
  path: '/manage/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAssetRoute = ManageAssetRouteImport.update({
  id: '/manage/asset',
  path: '/manage/asset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/manage/asset': typeof ManageAssetRoute
  '/manage/form': typeof ManageFormRoute
  '/manage/location': typeof ManageLocationRoute
  '/manage/login': typeof ManageLoginRoute
  '/manage/redirect': typeof ManageRedirectRoute
  '/manage/reset': typeof ManageResetRoute
  '/manage/social': typeof ManageSocialRoute
  '/manage/users': typeof ManageUsersRoute
  '/manage': typeof ManageIndexRoute
}
export interface FileRoutesByTo {
  '/manage/asset': typeof ManageAssetRoute
  '/manage/form': typeof ManageFormRoute
  '/manage/location': typeof ManageLocationRoute
  '/manage/login': typeof ManageLoginRoute
  '/manage/redirect': typeof ManageRedirectRoute
  '/manage/reset': typeof ManageResetRoute
  '/manage/social': typeof ManageSocialRoute
  '/manage/users': typeof ManageUsersRoute
  '/manage': typeof ManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/manage/asset': typeof ManageAssetRoute
  '/manage/form': typeof ManageFormRoute
  '/manage/location': typeof ManageLocationRoute
  '/manage/login': typeof ManageLoginRoute
  '/manage/redirect': typeof ManageRedirectRoute
  '/manage/reset': typeof ManageResetRoute
  '/manage/social': typeof ManageSocialRoute
  '/manage/users': typeof ManageUsersRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/manage/asset'
    | '/manage/form'
    | '/manage/location'
    | '/manage/login'
    | '/manage/redirect'
    | '/manage/reset'
    | '/manage/social'
    | '/manage/users'
    | '/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/manage/asset'
    | '/manage/form'
    | '/manage/location'
    | '/manage/login'
    | '/manage/redirect'
    | '/manage/reset'
    | '/manage/social'
    | '/manage/users'
    | '/manage'
  id:
    | '__root__'
    | '/manage/asset'
    | '/manage/form'
    | '/manage/location'
    | '/manage/login'
    | '/manage/redirect'
    | '/manage/reset'
    | '/manage/social'
    | '/manage/users'
    | '/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ManageAssetRoute: typeof ManageAssetRoute
  ManageFormRoute: typeof ManageFormRoute
  ManageLocationRoute: typeof ManageLocationRoute
  ManageLoginRoute: typeof ManageLoginRoute
  ManageRedirectRoute: typeof ManageRedirectRoute
  ManageResetRoute: typeof ManageResetRoute
  ManageSocialRoute: typeof ManageSocialRoute
  ManageUsersRoute: typeof ManageUsersRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/users': {
      id: '/manage/users'
      path: '/manage/users'
      fullPath: '/manage/users'
      preLoaderRoute: typeof ManageUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/social': {
      id: '/manage/social'
      path: '/manage/social'
      fullPath: '/manage/social'
      preLoaderRoute: typeof ManageSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/reset': {
      id: '/manage/reset'
      path: '/manage/reset'
      fullPath: '/manage/reset'
      preLoaderRoute: typeof ManageResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/redirect': {
      id: '/manage/redirect'
      path: '/manage/redirect'
      fullPath: '/manage/redirect'
      preLoaderRoute: typeof ManageRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/login': {
      id: '/manage/login'
      path: '/manage/login'
      fullPath: '/manage/login'
      preLoaderRoute: typeof ManageLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/location': {
      id: '/manage/location'
      path: '/manage/location'
      fullPath: '/manage/location'
      preLoaderRoute: typeof ManageLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/form': {
      id: '/manage/form'
      path: '/manage/form'
      fullPath: '/manage/form'
      preLoaderRoute: typeof ManageFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/asset': {
      id: '/manage/asset'
      path: '/manage/asset'
      fullPath: '/manage/asset'
      preLoaderRoute: typeof ManageAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ManageAssetRoute: ManageAssetRoute,
  ManageFormRoute: ManageFormRoute,
  ManageLocationRoute: ManageLocationRoute,
  ManageLoginRoute: ManageLoginRoute,
  ManageRedirectRoute: ManageRedirectRoute,
  ManageResetRoute: ManageResetRoute,
  ManageSocialRoute: ManageSocialRoute,
  ManageUsersRoute: ManageUsersRoute,
  ManageIndexRoute: ManageIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
